### ISSUE TITLE
Implement `size_of` and `cast`?

### ISSUE THREAD

**Issue by playXE** [transistorfet/molten#1]
I think this language must have `cast` and `size_of` functions. 
Why `cast`(transmute) and `size_of`? These function useful for pointer operations,e.g
```rust
struct Point {
       x: Int,
       y: Int,
}

let pointer = malloc(size_of(Int) + size_of(Int));
let point = cast<Point>(pointer); // casts pointer to `Point`,x  = 0 and y = 0
```

**Comment by transistorfet** [comment]
Thank you for your comment.  This language is intended to be garbage collected, and the builtin function "malloc" will be unavailable when I finally implement GC.

That said, because I've defined malloc internally as returning a type variable, the type variable can be implicitly cast to any pointer type. As in:
```
let point: Point = malloc(8)
```
Even though this is very bad for memory safety.  It's just that sizeof that would be needed in this case.  I suppose for completeness it would be nice to have, even though you would not normally be able to access malloc in order to use it.

**Comment by playXE** [comment]
@transistorfet you don't think about making garbage collector optional?

**Comment by transistorfet** [comment]
Ideally I'd like to have accurate tracing garbage collection, which can't easily be made optional, although I might just add Boehm as a stop gap.  The ML languages generally use garbage collection, and Molten is meant to be a high level language, so it makes more sense to have garbage collection.  I'm generally not in favour of manual memory management, hence why I'm using Rust. =P

I've added a sizeof() builtin in https://github.com/transistorfet/molten/commit/851e3efe3d06e4e687994c8bcd66ea1d37be3c68
It only works with a value that has a certain type at the moment.  Making it take a direct type reference would require adding a new AST element, I think, which I'm a bit iffy on for the time being.  Can you think of any other functions that might need to take a direct type other than sizeof/offsetof?

**Comment by playXE** [comment]
I think functions like this: `memcpy, to_bits` and etc. Also you may ask questions about compiler there (Programming language design): https://discord.gg/tUY3MXR

**Comment by transistorfet** [comment]
I'm closing this issue because I've now added a garbage collector, and the sizeof function has already been added.  Memory should now be allocated using the `molten_malloc` builtin.  Technically the GC is optional (--no-gc) but the compiler automatically injects calls to `molten_malloc` when boxing typevars, which would cause a memory leak, so it's not really feasible to use without GC.
